Remove guava suppliers
ExpediaGroup/styx pull request #765
Opened 2021-11-29 16:30 UTC by kvosper

This is a continuation of the Guava removal https://github.com/ExpediaGroup/styx/pull/755

Guava suppliers were used for memoization. This has been replaced with internal code.

2022-02-18 17:37 UTC, ryanellison submitted a review, later dismissed
Looks good, just needs a rebase.

2022-02-18 17:57 UTC, ryanellison requested changes
Just a couple rebase issues to clean up, otherwise 👍

2022-02-18 17:57 UTC, ryanellison commented on components/proxy/src/main/java/com/hotels/styx/admin/handlers/LoggingConfigurationHandler.java
> +<<<<<<< HEAD
Rebase cleanup needed

2022-03-01 17:12 UTC, ryanellison approved these changes

2022-03-01 17:13 UTC, imccunn approved these changes

2022-03-01 17:16 UTC, merged