Update netty-tcnative, reactor dependency versions
ExpediaGroup/styx pull request #784
Opened 2022-03-23 19:05 UTC by ryanellison

2022-03-24 11:08 UTC, kvosper requested changes
When running `make e2e` I got this error:
```[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.5:report (report) on project styx-api: An error has occurred in JaCoCo report generation.: Error while creating report: Error while analyzing``` ... ```styx/components/api/target/classes/com/hotels/styx/api/extension/service/spi/RegistryChangesKt.class. Unexpected SMAP line: *S KotlinDebug -> [Help 1]```

2022-03-24 14:03 UTC, battaglia-v approved these changes

2022-03-30 15:15 UTC, battaglia-v approved these changes

2022-03-30 15:51 UTC, kvosper approved these changes
Since failure also occurs on master, I am approving this.

2022-03-30 20:25 UTC, ryanellison commented
Issue created for make e2e failures discovered during testing of this PR: https://github.com/ExpediaGroup/styx/issues/788

2022-03-30 20:26 UTC, merged